name: Jeyser site CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Build
        run: |
          git clone https://github.com/n7consulting/jeyser-site.git \
          && cd jeyser-site \
          && yarn install \
          && bin/retrieve-documentation \
          && yarn gatsby build
